### ISSUE TITLE
如何加载jar文件

### ISSUE THREAD

**Issue by wurangbo** [hemin1003/spring-boot-study#1]
现在系统中有多个jar包，一个jar包对应一个业务模块，有对应的 controller，service，dao，如何做到按顺序启动？

**Comment by hemin1003** [comment]
是指jar的顺序执行吧，像这种情况，就是微服务架构了，可以看看另一个spring-cloud-study项目。所以，要么写脚本启动，要么做服务编排吧

**Comment by wurangbo** [comment]
有一个问题请教，我们用maven搭建了一个多module的项目（每个module都包含rest接口）。由多个jar聚合成了一个war，打包时jar文件拷贝到了lib目录下，但是运行时发现rest接口没有启动。这个需要设置哪里？
